# Generated by Django 4.2.7 on 2023-11-17 21:21

from django.db import migrations, models

import account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default=account.models.create_default_image_filepath, max_length=250, null=True, upload_to=account.models.create_profile_image_filepath),
        ),
    ]
