# Generated by Django 4.2.4 on 2023-11-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.IntegerField(max_length=10),
        ),
    ]
